<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0"/>
    <PackageVersion Include="FFMpegCore" Version="5.4.0"/>
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0"/>
    <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.7.1"/>
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11"/>
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.11"/>
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.11"/>
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11"/>
    <PackageVersion Include="Octokit" Version="14.0.0"/>
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556"/>
    <PackageVersion Include="System.Threading.RateLimiting" Version="10.0.11"/>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Google.Cloud.TextToSpeech.V1" Version="3.18.0"/>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.1"/>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
    <PackageVersion Include="xunit" Version="2.9.3"/>
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0"/>
  </ItemGroup>
</Project>