using System.Text.Json;

using WoWVoxPack.AddOns;
using WoWVoxPack.AddOns.Callouts;
using WoWVoxPack.TTS;

namespace WoWVoxPack.UnitTests;

public class CalloutNameVocabularyTests
{
    [Fact]
    public void Parse_SortsCaseInsensitivelyAndDropsBlanksAndComments()
    {
        IReadOnlyList<string> names = CalloutNameVocabulary.Parse(
        [
            "Soak",
            string.Empty,
            "# generated by .github/workflows/update.yml",
            "  Dispel  ",
            "Beam"
        ]);

        Assert.Equal(["Beam", "Dispel", "Soak"], names);
    }

    [Fact]
    public void Parse_RemovesDuplicatesIgnoringCase()
    {
        Assert.Equal(["Soak"], CalloutNameVocabulary.Parse(["Soak", "soak"]));
    }

    [Fact]
    public void Parse_KeepsNumericNames()
    {
        Assert.Equal(["1", "10", "2"], CalloutNameVocabulary.Parse(["2", "10", "1"]));
    }

    [Fact]
    public void Parse_TreatsDifferentUpstreamHeadersIdentically()
    {
        IReadOnlyList<string> nsrt = CalloutNameVocabulary.Parse(
            ["# Northern Sky Raid Tools callout vocabulary.", "Soak", "Spread"]);
        IReadOnlyList<string> lorrgs = CalloutNameVocabulary.Parse(
            ["# Lorrgs player-reminder vocabulary.", "Spread", "Soak"]);

        Assert.Equal(nsrt, lorrgs);
    }

    [Fact]
    public void TrackedLorrgsFile_CoversExportablePlayersButNotHistoricalItems()
    {
        IReadOnlyList<string> names =
            CalloutNameVocabulary.Load(FindRepoFile("lorrgs-vocabulary.txt"));

        Assert.Equal(215, names.Count);
        Assert.Contains("Anti-Magic Shell", names);       // Hidden defensive.
        Assert.Contains("Blood Fury", names);             // Racial.
        Assert.Contains("Pain Suppression", names);       // External.
        Assert.Contains("Algeth'ar Puzzle Box", names);   // Current trinket.
        Assert.Contains("Silvermoon Health Potion", names);
        Assert.Contains("Healthstone", names);
        Assert.DoesNotContain("Araz's Ritual Forge", names);
        Assert.DoesNotContain("Tempered Potion", names);
    }

    [Fact]
    public void TrackedLorrgsFile_HasNoCuratedJsonOverlap()
    {
        IReadOnlyList<string> lorrgs =
            CalloutNameVocabulary.Load(FindRepoFile("lorrgs-vocabulary.txt"));
        using JsonDocument curated = JsonDocument.Parse(File.ReadAllText(
            FindRepoFile("src/WoWVoxPack.AddOns.Callouts/Callouts_Sounds.json")));
        List<string> curatedNames = curated.RootElement.EnumerateArray()
            .Select(entry => entry.GetProperty("DisplayName").GetString()!)
            .ToList();

        Assert.Empty(lorrgs.Intersect(curatedNames, StringComparer.OrdinalIgnoreCase));
    }

    [Fact]
    public void SharedOverrides_PreserveMigratedLorrgsPronunciations()
    {
        IReadOnlyDictionary<string, PronunciationOverride> overrides =
            CalloutPronunciation.LoadOverrides(FindRepoFile(
                "src/WoWVoxPack.AddOns.Callouts/CalloutPronunciations.json"));

        IReadOnlyList<CalloutRegistration> registrations = CalloutVocabulary.Merge(
            [], ["Innervate", "Invoke Chi-Ji, the Red Crane", "Invoke Yu'lon, the Jade Serpent"],
            overrides);

        Assert.Contains(registrations,
            entry => entry.SoundFile.DisplayName == "Innervate"
                     && entry.SoundFile.Ssml!.Contains("ˈɪnɚveɪt"));
        Assert.Contains(registrations,
            entry => entry.SoundFile.DisplayName == "Invoke Yu'lon, the Jade Serpent"
                     && entry.SoundFile.Ssml!.Contains("ˈjuːlɒn"));
        Assert.Contains(registrations,
            entry => entry.SoundFile.DisplayName == "Invoke Chi-Ji, the Red Crane"
                     && entry.SoundFile.Ssml!.Contains("tʃiːdʒiː"));
    }

    [Fact]
    public void TrackedRetirement_PreservesTheOldChiJiKeyWithoutDuplicateAudio()
    {
        List<string> retired = JsonSerializer.Deserialize<List<string>>(File.ReadAllText(
            FindRepoFile("src/WoWVoxPack.AddOns.Callouts/RetiredCallouts.json")))!;
        IReadOnlyDictionary<string, PronunciationOverride> overrides =
            CalloutPronunciation.LoadOverrides(FindRepoFile(
                "src/WoWVoxPack.AddOns.Callouts/CalloutPronunciations.json"));

        IReadOnlyList<CalloutRegistration> registrations = CalloutVocabulary.Merge(
            [], ["Invoke Chi-Ji, the Red Crane"], overrides, retired);

        Assert.Contains(registrations,
            entry => entry.SoundFile.DisplayName == "Invoke Chi-Ji, the Red Crane");
        Assert.Contains(registrations,
            entry => entry.SoundFile.DisplayName == "Invoke Chi-ji, the Red Crane");
        Assert.Single(registrations.Select(entry => entry.SoundFile.FileName)
            .Distinct(StringComparer.Ordinal));
    }

    [Fact]
    public void TrackedVocabulary_ContainsTheApprovedSpellShorthand()
    {
        string[] approved =
        [
            "Puzzle Box", "AMS", "AMZ", "Cheetah", "Eagle", "Turtle", "Wings", "BoP",
            "Sac", "Spellwarding", "Lust", "Cloak", "Convoke", "Healthstone", "Demo Shout",
            "Bubble", "Ebon Might", "Enraged Regen", "Fel Dev", "Trees", "Fort Brew",
            "Frostwyrm", "Fel Ravager", "Imp Lord", "Healing Tide", "Incarn", "Tree of Life",
            "Chi-ji", "Niuzao", "Xuen", "Yu'lon", "Cocoon", "Pain Sup", "PI", "Barrier",
            "Radiance", "Rally", "Ankh", "Spell Reflect", "Spirit Link", "Roar", "Darkglare",
            "Tyrant", "Doomguard", "Infernal", "Tip", "Tranq", "Wind Rush", "Uppies", "Wall",
            "Meta"
        ];
        IReadOnlyList<CalloutRegistration> registrations = LoadTrackedRegistrations();

        foreach (string displayName in approved)
        {
            Assert.Contains(registrations,
                entry => entry.SoundFile.DisplayName.Equals(displayName, StringComparison.Ordinal));
        }
    }

    [Theory]
    [InlineData("Metamorphosis", "Meta")]
    [InlineData("Void Metamorphosis", "Meta")]
    [InlineData("Ultimate Penitence", "Uppies")]
    [InlineData("Shield Wall", "Wall")]
    [InlineData("Invoke Chi-Ji, the Red Crane", "Chi-ji")]
    public void TrackedVocabulary_KeepsFormalAndShorthandRecordingsIndependent(
        string formalName,
        string shorthandName)
    {
        IReadOnlyList<CalloutRegistration> registrations = LoadTrackedRegistrations();
        CalloutRegistration formal = Assert.Single(registrations,
            entry => entry.SoundFile.DisplayName.Equals(formalName, StringComparison.Ordinal));
        CalloutRegistration shorthand = Assert.Single(registrations,
            entry => entry.SoundFile.DisplayName.Equals(shorthandName, StringComparison.Ordinal));

        Assert.NotEqual(formal.SoundFile.FileName, shorthand.SoundFile.FileName);
        Assert.Contains(formalName, formal.MediaKeys);
        Assert.Empty(shorthand.MediaKeys);
    }

    [Fact]
    public void CuratedInitialisms_HaveExplicitLetterNameIpa()
    {
        using JsonDocument curated = JsonDocument.Parse(File.ReadAllText(FindRepoFile(
            "src/WoWVoxPack.AddOns.Callouts/Callouts_Sounds.json")));
        Dictionary<string, JsonElement> entries = curated.RootElement.EnumerateArray()
            .ToDictionary(
                entry => entry.GetProperty("DisplayName").GetString()!,
                StringComparer.Ordinal);

        Assert.Equal("<speak><phoneme alphabet=\"ipa\" ph=\"eɪ.ɛm.ɛs\">AMS</phoneme></speak>",
            entries["AMS"].GetProperty("SSML").GetString());
        Assert.Equal("<speak><phoneme alphabet=\"ipa\" ph=\"eɪ.ɛm.zi\">AMZ</phoneme></speak>",
            entries["AMZ"].GetProperty("SSML").GetString());
        Assert.Equal("Bop", entries["BoP"].GetProperty("Text").GetString());
        Assert.Equal("<speak><phoneme alphabet=\"ipa\" ph=\"pi.aɪ\">PI</phoneme></speak>",
            entries["PI"].GetProperty("SSML").GetString());
    }

    [Fact]
    public void CuratedSounds_HaveUniqueDisplayNamesAndFileNames()
    {
        List<SoundFile> curated = AddOnBuilder.LoadSoundFileJson(FindRepoFile(
            "src/WoWVoxPack.AddOns.Callouts/Callouts_Sounds.json"));

        Assert.Equal(curated.Count,
            curated.Select(sound => sound.DisplayName).Distinct(StringComparer.OrdinalIgnoreCase).Count());
        Assert.Equal(curated.Count,
            curated.Select(sound => sound.FileName).Distinct(StringComparer.OrdinalIgnoreCase).Count());
    }

    [Fact]
    public void TrackedVocabulary_DoesNotContainRejectedSpellShorthand()
    {
        string[] rejected =
        [
            "Army", "Eons", "Frenzied Regen", "Pillar", "Dilation", "Karma", "Magi",
            "Vamp Blood", "Vamp Embrace", "Wake", "Zen Med"
        ];
        IReadOnlyList<CalloutRegistration> registrations = LoadTrackedRegistrations();

        foreach (string displayName in rejected)
        {
            Assert.DoesNotContain(registrations,
                entry => entry.SoundFile.DisplayName.Equals(displayName, StringComparison.Ordinal));
        }
    }

    private static IReadOnlyList<CalloutRegistration> LoadTrackedRegistrations() =>
        new CalloutsVocabularyProvider(
            FindRepoFile("src/WoWVoxPack.AddOns.Callouts/Callouts_Sounds.json"),
            FindRepoFile("src/WoWVoxPack.AddOns.Callouts/CalloutPronunciations.json"),
            FindRepoFile("lorrgs-vocabulary.txt"),
            FindRepoFile("src/WoWVoxPack.AddOns.Callouts/RetiredCallouts.json"))
        .Registrations;

    private static string FindRepoFile(string fileName)
    {
        DirectoryInfo? directory = new(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, fileName)))
        {
            directory = directory.Parent;
        }

        Assert.NotNull(directory);
        return Path.Combine(directory.FullName, fileName);
    }
}
