<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WoWVoxPack.Core\WoWVoxPack.Core.csproj"/>
    <ProjectReference Include="..\..\src\WoWVoxPack.AddOns.Callouts\WoWVoxPack.AddOns.Callouts.csproj"/>
    <ProjectReference Include="..\..\src\WoWVoxPack.AddOns.BigWigs_Voice\WoWVoxPack.AddOns.BigWigs_Voice.csproj"/>
    <ProjectReference Include="..\..\src\WoWVoxPack.AddOns.BigWigs_Countdown\WoWVoxPack.AddOns.BigWigs_Countdown.csproj"/>
    <ProjectReference Include="..\..\src\WoWVoxPack.AddOns.ExBoss\WoWVoxPack.AddOns.ExBoss.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>

</Project>