using System.Text;

using WoWVoxPack.AddOns;

namespace WoWVoxPack.AddOns.Callouts;

/// <summary>Generates literal LibSharedMedia registrations for one NSRT voice pack.</summary>
public static class NorthernSkyRaidToolsLuaFile
{
    public static string Render(AddOn addOn, IEnumerable<CalloutRegistration> registrations)
    {
        string voice = addOn.TtsSettings.Voice?.ToString() ?? string.Empty;
        StringBuilder lua = new();

        lua.Append("-- Generated by WoWVoxPack. Do not edit.\n\n");
        lua.Append("-- LibStub(name, true) is the silent form: nil instead of an error.\n");
        lua.Append("local LSM = LibStub and LibStub(\"LibSharedMedia-3.0\", true)\n");
        lua.Append("if not LSM then return end\n\n");
        lua.Append("local voice = \"").Append(EscapeLua(voice)).Append("\"\n");
        lua.Append("local activeVoice = _G.WoWVoxPacksNorthernSkyRaidToolsVoice\n");
        lua.Append("if activeVoice and activeVoice ~= voice then\n");
        lua.Append("    print(\"WoWVoxPacks: another Northern Sky Raid Tools voice pack is already active (\"\n");
        lua.Append("        .. activeVoice .. \"); \" .. voice .. \" registered nothing.\")\n");
        lua.Append("    return\n");
        lua.Append("end\n");
        lua.Append("_G.WoWVoxPacksNorthernSkyRaidToolsVoice = voice\n\n");
        lua.Append("local path = \"Interface\\\\AddOns\\\\")
            .Append(EscapeLua(addOn.AddOnDirectoryName))
            .Append("\\\\Sounds\\\\\"\n");

        HashSet<string> renderedKeys = new(
            addOn.SoundFiles.Select(soundFile => soundFile.Key),
            StringComparer.OrdinalIgnoreCase);

        foreach (CalloutRegistration registration in registrations)
        {
            // A reuse-only registration whose recording is gone from this pack has no file to
            // point at; registering it would hand LibSharedMedia a dead path.
            if (registration.ReuseExistingAudioOnly
                && !renderedKeys.Contains(registration.SoundFile.Key))
            {
                continue;
            }

            foreach (string mediaKey in registration.MediaKeys)
            {
                lua.Append("LSM:Register(\"sound\", \"")
                    .Append(EscapeLua(mediaKey))
                    .Append("\", path .. \"")
                    .Append(EscapeLua(registration.SoundFile.FileName))
                    .Append("\")\n");
            }
        }

        return lua.ToString();
    }

    private static string EscapeLua(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
