#!/usr/bin/env python3
"""Extract player-reminder names from a lorrgs source checkout."""

from __future__ import annotations

import argparse
import importlib
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any


LORRGS_REPOSITORY = "https://github.com/gitarrg/lorrgs"
HEALTHSTONE_SPELL_ID = 6262
ABILITY_COLLECTIONS = ("all_spells", "all_buffs", "all_debuffs", "all_events")


def sort_unique_names(names: Iterable[str]) -> list[str]:
    """Return stable names while refusing ambiguous case-only collisions."""
    by_casefold: dict[str, str] = {}
    for name in names:
        folded = name.casefold()
        existing = by_casefold.get(folded)
        if existing is not None and existing != name:
            raise ValueError(
                f"case-insensitive duplicate ability names: {existing!r} and {name!r}")
        by_casefold[folded] = name

    return sorted(by_casefold.values(), key=lambda name: (name.casefold(), name))


def collect_names(
    specs: Iterable[Any],
    item_type: type,
    current_items: Iterable[Any],
    always_current_item_ids: set[int],
) -> list[str]:
    """Collect non-items and the explicitly current subset of lorrgs items."""
    current_object_ids = {id(item) for item in current_items}
    names: list[str] = []

    for spec in specs:
        for collection_name in ABILITY_COLLECTIONS:
            for ability in getattr(spec, collection_name):
                is_item = isinstance(ability, item_type)
                is_current_item = (
                    id(ability) in current_object_ids
                    or getattr(ability, "spell_id", None) in always_current_item_ids
                )
                if is_item and not is_current_item:
                    continue

                name = ability.name
                if not name:
                    raise ValueError(
                        f"empty ability name for spell ID {getattr(ability, 'spell_id', 'unknown')}")
                names.append(name)

    return sort_unique_names(names)


def render_vocabulary(
    names: Iterable[str], repository: str, commit: str, season: str
) -> str:
    """Render provenance and names in a reproducible text format."""
    header = [
        "# Lorrgs player-reminder vocabulary.",
        f"# Source: {repository}",
        f"# Source commit: {commit}",
        f"# Active season: {season}",
        "# Generated by scripts/extract_lorrgs_vocabulary.py. Do not edit by hand.",
    ]
    return "\n".join([*header, *sort_unique_names(names)]) + "\n"


def write_vocabulary(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")


def resolve_commit(source: Path, supplied_commit: str | None) -> str:
    if supplied_commit:
        return supplied_commit
    return subprocess.check_output(
        ["git", "-C", str(source), "rev-parse", "HEAD"], text=True
    ).strip()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path, help="lorrgs checkout")
    parser.add_argument("--source-commit", help="commit recorded in the output header")
    parser.add_argument("--output", required=True, type=Path, help="output vocabulary path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source = args.source.resolve()
    sys.path.insert(0, str(source))

    from lorgs.data.season import CURRENT_SEASON
    from lorgs.models.wow_item import WowItem
    from lorgs.models.wow_spec import WowSpec

    expansion_name = CURRENT_SEASON.slug.rsplit("_s", 1)[0]
    expansion = importlib.import_module(f"lorgs.data.expansions.{expansion_name}")
    consumables_name = f"{expansion_name.upper()}_CONSUMABLES"
    current_consumables = getattr(expansion, consumables_name)
    current_items = [*CURRENT_SEASON.trinkets, *current_consumables]

    names = collect_names(
        WowSpec.list(),
        WowItem,
        current_items,
        always_current_item_ids={HEALTHSTONE_SPELL_ID},
    )
    content = render_vocabulary(
        names,
        repository=LORRGS_REPOSITORY,
        commit=resolve_commit(source, args.source_commit),
        season=CURRENT_SEASON.slug,
    )
    write_vocabulary(args.output, content)
    print(f"Wrote {len(names)} names to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
