name: Create release
on:
  pull_request:
    types: [closed]
    branches: [ci/*]
jobs:
  create-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set release tag
        id: set-release-tag
        run: |
          echo "RELEASE_TAG=$(cat bigwigs-voice-version.txt)" >> $GITHUB_OUTPUT
      - name: Package artifacts
        run: ./scripts/package.sh
      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-release-tag.outputs.RELEASE_TAG }}
          name: Release ${{ steps.set-release-tag.outputs.RELEASE_TAG }}
          body: |
            Automatically created by the update workflow.
          draft: false
          prerelease: false
          files: |
            ./dist/*.zip
            ./bigwigs-voice-version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}