name: Check for updates
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  check-bigwigs-voice-version:
    runs-on: ubuntu-latest
    outputs:
      bigwigs_version: ${{ steps.compare-versions.outputs.bigwigs_version }}
    steps:
      - name: Get latest BigWigsVoice release
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: BigWigsMods
          repo: BigWigs_Voice
          excludes: prerelease, draft

      - name: Write version to file
        run: echo "${{ steps.get_latest_release.outputs.release }}" > version.txt

      - name: Get previous version
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/KogasaPls/WoWVoxPacks/releases/latest
          | jq -r '.assets[] | select(.name == "bigwigs-voice-version.txt") | .browser_download_url' 
          | xargs curl -L -o previous-version.txt

      - name: Compare versions
        id: compare-versions
        run: |
          if [ ! -f previous-version.txt ]; then
            echo "No previous version detected"
            echo "bigwigs_version=$(cat version.txt)" >> $GITHUB_OUTPUT
          elif [ "$(cat version.txt)" != "$(cat previous-version.txt)" ]; then
            echo "New version detected (old: $(cat previous-version.txt), new: $(cat version.txt))"
            echo "bigwigs_version=$(cat version.txt)" >> $GITHUB_OUTPUT
          else
            echo "No new version detected"
          fi

      - name: Upload new version
        if: ${{ steps.compare-versions.outputs.bigwigs_version != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: bigwigs-voice-version
          path: version.txt