import importlib.util
import subprocess
import tempfile
import unittest
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]

spec = importlib.util.spec_from_file_location(
    "release_notes", REPOSITORY_ROOT / "scripts" / "release_notes.py"
)
release_notes = importlib.util.module_from_spec(spec)
spec.loader.exec_module(release_notes)


class RenderTests(unittest.TestCase):
    def test_notes_carry_the_commits_and_both_callout_lists(self):
        rendered = release_notes.render(
            "v12.1.0-r9",
            "2026-08-21",
            ["fix pronunciation", "fold the Callouts sounds into the NSRT pack"],
            ["Adrenaline Rush"],
            ["Old Callout"],
            "https://example.invalid/compare/v12.1.0-r8...v12.1.0-r9",
        )

        self.assertIn("## v12.1.0-r9 (2026-08-21)", rendered)
        self.assertIn(
            "[Full Changelog](https://example.invalid/compare/v12.1.0-r8...v12.1.0-r9)",
            rendered,
        )
        self.assertIn("- fix pronunciation", rendered)
        self.assertIn("### New callouts\n\n- Adrenaline Rush", rendered)
        self.assertIn("### Removed callouts\n\n- Old Callout", rendered)

    def test_an_empty_section_is_omitted_rather_than_left_bare(self):
        rendered = release_notes.render("v1", "2026-08-21", ["only a commit"], [], [])

        self.assertNotIn("New callouts", rendered)
        self.assertNotIn("Removed callouts", rendered)

    def test_a_long_list_states_what_it_left_out(self):
        """A season's first sync moves hundreds of names; a silent cut reads as the whole list."""
        names = [f"Callout {index:03d}" for index in range(100)]

        rendered = release_notes.render("v1", "2026-08-21", [], names, [], limit=40)

        self.assertIn("- Callout 039", rendered)
        self.assertNotIn("- Callout 040", rendered)
        self.assertIn("- ... and 60 more", rendered)


class VocabularyDiffTests(unittest.TestCase):
    def test_added_and_removed_names_are_read_from_the_diff(self):
        added, removed = release_notes.parse_vocabulary_diff(
            "--- a/nsrt-vocabulary.txt\n"
            "+++ b/nsrt-vocabulary.txt\n"
            "@@ -1,2 +1,2 @@\n"
            "+Soak Left\n"
            "-Old Name\n"
        )

        self.assertEqual((["Soak Left"], ["Old Name"]), (added, removed))

    def test_comments_and_blank_lines_are_not_callouts(self):
        added, removed = release_notes.parse_vocabulary_diff(
            "+++ b/nsrt-vocabulary.txt\n+# Regenerated by the update workflow\n+\n+Real Callout\n"
        )

        self.assertEqual((["Real Callout"], []), (added, removed))

    def test_a_name_that_only_moved_between_files_is_not_reported(self):
        """The lorrgs import moved names between vocabularies without changing what speaks."""
        added, removed = release_notes.parse_vocabulary_diff(
            "--- a/nsrt-vocabulary.txt\n-Tranq\n+++ b/lorrgs-vocabulary.txt\n+Tranq\n+Barkskin\n"
        )

        self.assertEqual((["Barkskin"], []), (added, removed))


class GitTests(unittest.TestCase):
    """The parts that read history, exercised against a real repository."""

    def setUp(self):
        self.directory = Path(tempfile.mkdtemp())
        self.addCleanup(subprocess.run, ["rm", "-rf", str(self.directory)])
        self.git("init", "-q", "-b", "main")
        self.git("config", "user.email", "test@example.invalid")
        self.git("config", "user.name", "Test")
        self.git("config", "commit.gpgsign", "false")

    def git(self, *arguments):
        return release_notes.git(*arguments, repository=self.directory)

    def commit(self, message, **files):
        for name, content in files.items():
            (self.directory / name.replace("__", "-")).write_text(content, encoding="utf-8")
        log = self.directory / "log.txt"
        log.write_text(f"{log.read_text() if log.exists() else ''}{message}\n", encoding="utf-8")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", message)

    def test_the_span_starts_at_the_previous_release_tag(self):
        self.commit("first", **{"nsrt__vocabulary.txt": "Soak\n"})
        self.git("tag", "v1.0.0-r1")
        self.commit("second", **{"nsrt__vocabulary.txt": "Soak\nBait\n"})
        self.commit("third", **{"nsrt__vocabulary.txt": "Bait\n"})

        previous = release_notes.previous_tag("HEAD", self.directory)

        self.assertEqual("v1.0.0-r1", previous)
        self.assertEqual(
            ["third", "second"],
            release_notes.commit_subjects(previous, "HEAD", self.directory),
        )
        self.assertEqual(
            (["Bait"], ["Soak"]),
            release_notes.vocabulary_changes(previous, "HEAD", self.directory),
        )

    def test_releasing_a_tag_that_already_exists_spans_back_to_the_release_before_it(self):
        """A rerun on `push: tags` has the tag; describing from the ref would span nothing."""
        self.commit("first")
        self.git("tag", "v1.0.0-r1")
        self.commit("second")
        self.git("tag", "v1.0.0-r2")

        previous = release_notes.previous_tag("HEAD", self.directory, "v1.0.0-r2")

        self.assertEqual("v1.0.0-r1", previous)
        self.assertEqual(
            ["second"], release_notes.commit_subjects(previous, "HEAD", self.directory)
        )

    def test_a_release_sitting_on_this_commit_is_the_previous_release(self):
        """Cutting r2 with r1 on HEAD reports nothing new, not r1's commits a second time."""
        self.commit("first")
        self.commit("already released")
        self.git("tag", "v1.0.0-r1")

        previous = release_notes.previous_tag("HEAD", self.directory, "v1.0.0-r2")

        self.assertEqual("v1.0.0-r1", previous)
        self.assertEqual([], release_notes.commit_subjects(previous, "HEAD", self.directory))

    def test_the_first_release_reports_every_commit_and_no_callout_churn(self):
        self.commit("first", **{"nsrt__vocabulary.txt": "Soak\n"})
        self.commit("second")

        previous = release_notes.previous_tag("HEAD", self.directory)

        self.assertIsNone(previous)
        self.assertEqual(
            ["second", "first"],
            release_notes.commit_subjects(previous, "HEAD", self.directory),
        )
        self.assertEqual(
            ([], []), release_notes.vocabulary_changes(previous, "HEAD", self.directory)
        )

    def test_merge_commits_are_not_notes(self):
        self.commit("first")
        self.git("tag", "v1.0.0-r1")
        self.git("checkout", "-q", "-b", "side")
        self.commit("work on a branch")
        self.git("checkout", "-q", "main")
        self.git("merge", "-q", "--no-ff", "-m", "Merge pull request #28", "side")

        subjects = release_notes.commit_subjects("v1.0.0-r1", "HEAD", self.directory)

        self.assertEqual(["work on a branch"], subjects)


if __name__ == "__main__":
    unittest.main()
