import importlib.util
import sys
import tempfile
import unittest
from dataclasses import dataclass, field
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
EXTRACTOR_PATH = REPOSITORY_ROOT / "scripts" / "extract_lorrgs_vocabulary.py"


def load_extractor():
    spec = importlib.util.spec_from_file_location("extract_lorrgs_vocabulary", EXTRACTOR_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load {EXTRACTOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@dataclass
class Ability:
    name: str
    spell_id: int
    show: bool = True


@dataclass
class Item(Ability):
    pass


@dataclass
class Spec:
    all_spells: list[Ability] = field(default_factory=list)
    all_buffs: list[Ability] = field(default_factory=list)
    all_debuffs: list[Ability] = field(default_factory=list)
    all_events: list[Ability] = field(default_factory=list)


class ExtractLorrgsVocabularyTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.extractor = load_extractor()

    def test_collects_every_non_item_but_only_selected_items(self):
        visible = Ability("Visible Spell", 1, show=True)
        hidden = Ability("Hidden Defensive", 2, show=False)
        buff = Ability("External Buff", 3, show=False)
        debuff = Ability("Tracked Debuff", 4, show=False)
        event = Ability("Tracked Event", 5, show=False)
        old_item = Item("Old Trinket", 6)
        current_item = Item("Current Trinket", 7)
        healthstone = Item("Healthstone", 6262)
        spec = Spec(
            all_spells=[visible, hidden, old_item, current_item, healthstone],
            all_buffs=[buff],
            all_debuffs=[debuff],
            all_events=[event],
        )

        names = self.extractor.collect_names(
            [spec], Item, [current_item], always_current_item_ids={6262})

        self.assertEqual(
            [
                "Current Trinket",
                "External Buff",
                "Healthstone",
                "Hidden Defensive",
                "Tracked Debuff",
                "Tracked Event",
                "Visible Spell",
            ],
            names,
        )

    def test_rejects_case_only_name_collisions(self):
        with self.assertRaisesRegex(ValueError, "case-insensitive duplicate"):
            self.extractor.sort_unique_names(["Spell Name", "spell name"])

    def test_deduplicates_the_same_name_from_multiple_specs(self):
        self.assertEqual(
            ["Shared Spell"],
            self.extractor.sort_unique_names(["Shared Spell", "Shared Spell"]),
        )

    def test_rejects_empty_names(self):
        with self.assertRaisesRegex(ValueError, "empty ability name"):
            self.extractor.collect_names(
                [Spec(all_spells=[Ability("", 1)])],
                Item,
                [],
                always_current_item_ids={6262},
            )

    def test_render_records_provenance_and_stable_order(self):
        rendered = self.extractor.render_vocabulary(
            ["Zulu", "alpha"],
            repository="https://github.com/gitarrg/lorrgs",
            commit="abc123",
            season="midnight_s1",
        )

        self.assertEqual(
            "# Lorrgs player-reminder vocabulary.\n"
            "# Source: https://github.com/gitarrg/lorrgs\n"
            "# Source commit: abc123\n"
            "# Active season: midnight_s1\n"
            "# Generated by scripts/extract_lorrgs_vocabulary.py. Do not edit by hand.\n"
            "alpha\n"
            "Zulu\n",
            rendered,
        )

    def test_write_vocabulary_creates_the_requested_output(self):
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "nested" / "vocabulary.txt"

            self.extractor.write_vocabulary(output, "content\n")

            self.assertEqual("content\n", output.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
